Error Handling
==============
Andrey Antukh
:deckjs_theme: swiss
:deckjs_transition: fade
:navigation:
:status:
:source-highlighter: pygments
:pygments-style: friendly
:split:


[[historic-1]]
Let's start with some historic approach
---------------------------------------

**How we did things in C?**

.Api definition
[source, c]
----
MYAPI_ERROR get_object_size(MYAPIHandle h, int* returned_size);
----

[options="step"]
.Error handlign
[source, c]
----
int size;
if(get_object_size(h, &size) != MYAPI_SUCCESS) {
    // Error handling
}
----

<<<

.Api definition
[source, c]
----
int get_object_size(MYAPIHandle h, MYAPI_ERROR* error);
----

[options="step"]
.Error handling
[source, c]
----
MYAPIError error;
int size;
size = get_object_size(h, &error);
if(error != MYAPI_SUCCESS) {
    // Error handling
}
----

<<<

- Serves as example code to see where we came from.
- Seems very low level and hacky way to do error handling.
- Some modern languages uses similar ways of error handling :(

NULL Pointer
------------

Consist of usage of **null pointer** as result of erroneous operation.

[options="step"]
- It exists in almost all _modern_ languages.
- Represents a null pointer in a good portion of these "modern" languages.
- The source of all evil.

<<<

Demostration:

[source, java]
----
String version = computer.getSoundcard().getUSB().getVersion();
----

- What is happens if sound card does not exists?
- What is happens if sound card does not have usb?

**If sound card does not exists, the `getUSB()` call will raise a `NullPointerException`**

<<<

This is the way to do it in a classic way using java:

[source, java]
----
String version = "UNKNOWN";
if (computer != null) {
    Soundcard soundcard = computer.getSoundcard();
    if (soundcard != null) {
        USB usb = soundcard.getUSB();
        if (usb != null){
            version = usb.getVersion();
        }
    }
}
----

[options="step"]
- Seems very ugly
- Adding new conditions make it more ugly.
- **Seems should to be an other and better way to do it.**

<<<

Some languages offers sugar syntax for handling null values:

.Clojure
[source, clojure]
----
(some-> computer get-sound-card get-usb get-version)
----

.Groovy
[source, groovy]
----
String version = computer?.getSoundcard()?.getUSB()?.getVersion();
----

<<<

Some other languages offers the `Optional<T>` type:

.Java 7 (using Guava Library)
[source, java]
----
Optional<Version> version = Optional.absent();
Optional<SoundCard> soundcard = computer.getSoundcard();

if (soundcard.isPresent()) {
   Optional<Usb> usb = soundcard.get().getUSB();
   if (usb.isPresent()) {
       version = usb.get().getVersion();
   }
}
----

[options="step"]
- Looks very similar to handling with `NULL`.
- Seems add more accidental complexity without improving anything.

<<<

Java 8 add some improvements in this area:

[source, java]
----
String version = computer.flatMap(Computer::getSoundcard)
                         .flatMap(Soundcard::getUSB)
                         .map(USB::getVersion)
                         .orElse("UNKNOWN");
----

[options="step"]
- Better that java 7 version.
- Continues having a lot of accidental complexity.

<<<

**Clojure and `nil`**

[options="step"]
- Clojure inherits java's null pointer, called `nil` in Clojure.
- Clojure seems to embrace the null pointer.
- `nil` is a first class value and it can implement protocols.

<<<

[source, clojure]
----
(defprotocol ISum
  (add [_][_ _] "Sum two values"))

(extend-protocol ISum
  nil
  (add [_] 0)
  (add [_ x] (+ 0 (add x)))

  Long
  (add [x] x)
  (add [x y] (+ 0 (add y))))

(+ 1 nil)
;; => NullPointerException   clojure.lang.Numbers.ops (Numbers.java:961)

(add 1 nil)
;; => 1
----

<<<

Summary:

[options="step"]
- Null if a source of much of problems.
- Null should be avoided.
- Some languages has good improvements for handling with null pointers.
- Not works well with core.async (clojure).
- A fortuitous set of decisions in Clojure has reduced the magnitude of the problem.
- Null is opaque error, because it not contains any error message.
- There are better way to handling errors.


Exceptions
----------

**What is an exception?**

_An exception is an event that occurs during the execution of a
program that disrupts the normal flow of instructions._

[options="step"]
- Used as error handling mechanism in almost all object oriented languages.
- Is the next generation goto.
- Usually used for label ordinary errors such as failing to open a file
  as exceptional.

[options="step"]
====
Good literature about this:

- http://250bpm.com/blog:4
- http://stackoverflow.com/questions/1736146/why-is-exception-handling-bad
- http://blogs.atlassian.com/2011/05/exceptions_are_bad/
====
<<<

Exceptions breaks encapsulation and single resposability.

[source, python]
----
def read_report_file(name:str, owner:User) -> Report:
    try:
        path = os.path.join(REPORTS_DIR, name)
        file = io.open(path, "rt")
        return process_file_and_get_report(file, owner)

    except PermissionDeniend as e:
        send_notification_about_unauthorized_request(e, owner)
        raise e

    except FileNotFound as e:
        raise ReportNotFound("Report file does not exists") from e

    finally:
        file.close()
----

<<<

With previous example:

- It's a clear violation of the Single Responsibility Principle. By definition, anything
  function using a try/catch is doing at least two things: application logic and handling
  an error for one exception type. It only gets worse as more exception types are propagated
  up the call chain. And let’s not forget the finally clause! So that’s 1 responsibility for
  application logic, n responsibilities for n catch clauses, and 1 responsibility for the
  finally clause to do any clean up. **This does way too much.**
- It's a violation of the Open/Closed Principle. If you want to add another catch clause,
  you have to dive into the guts of a function.

[options="step"]
====
Summary:

- Exceptions are no so bad as `NULL`
- Exceptions can be used in a "good way".
- Can return more information about error message unlike NULL or Maybe/Optional
- Can works as goto and usually used like goto on popular object oriented languages.
- Exceptions should be used for exceptional cases (haskell have exceptions... but for
  exceptional cases)
====

[options="step"]
**But, we can do it better?**

Error as value
--------------

- Golang is good example of language designed for use that type of error handling.
- Using that in clojure is a quite natural as in Go.
- Can be used in almost all languages.
- Seems a old fashion way to handle errors (like C) but without hacks.

<<<

Let see an example using python.

Firstly define the validation functions:

[source, python]
----
def clean_email(params:dict):
    if re.match(params.get("email", ""), EMAIL_REGEX):
        return (params, None)
    return (None, "Please enter an email address")

def clean_phone(params:dict):
    if re.match(params.get("phone", ""), PHONE_REGEX):
        return (params, None)
    return (None, "Please enter your phone number in (555) 555-5555 format.")

def clean_state(params:dict):
    if params.get("state", "") in ["WA", "OR"]:
       return (params, None)
    return (None, "We only want people from Oregon or Washington, for some reason.")
----

<<<

Now, compose the previous validators functions in one more complex:

[source, python]
----
def validate_form(params):
    params, err = clean_email(params)
    if err:
       return err
    params, err = clean_phone(params)
    if err:
       return err
    params, err = clean_state(params)
    if err:
       return err
----

[options="step"]
**Obviously it can be improved...**

<<<

[source, python]
----
def validate_form(params):
    validators = [clean_email,
                  clean_phone,
                  clean_state]

    for validator in validators:
        params, err = validator(params)
        if err:
           return err,
----


[options="step"]
====
- It looks better and it's be much less verbose that the previous version.
- But, it still unexpressive.
====

[options="step"]
====
- Validation can be very verbose if the number of fields grows.
- The expressiveness of the used language can determine the usage of this technique.
- Python, Java, Groovy, Go, ... lang aren't good example of expressiveness.
====

[options="step"]
**Let see how we can done same thing with _Clojure_.**

<<<

Firstly, define the validation functions:

[source, clojure]
----
(defn clean-email [params]
  "Ensure (params :email) matches /\w@\w\.\w/"
  (if (re-find #"\w@\w\.\w" (params :email))
    [params nil]
    [nil "Please enter an email address"]))

(defn clean-phone [params]
  "Ensure phone number matches /\([0-9]{3}\) [0-9]{3}-[0-9]{4}/"
  (if (re-find #"\([0-9]{3}\) [0-9]{3}-[0-9]{4}" (params :phone))
    [params nil]
    [nil "Please enter your phone number in (555) 555-5555 format."]))

(defn clean-state [params]
  "Ensure state is one of OR or WA. Cascadians unite!"
  (case (params :state)
    "WA" [params nil]
    "OR" [params nil]
    [nil "We only want people from Oregon or Washington, for some reason."]))
----

<<<

This is a first atempt of compose the previously validators:

[source,clojure]
----
(defn clean-contact [params]
  (let [[params err] (clean-email params)
        [params err] (if (nil? err) (clean-phone params) [nil err])
        [params err] (if (nil? err) (clean-state params) [nil err])]
    [params err])
----

[options="step"]
- It has less code lines that python.
- Looks ugly!
- Can we do it better?

<<<

Define a function for that will help in validation composition.

[source, clojure]
----
(defn apply-or-error [f [val err]]
  (if (nil? err)
    (f val)
    [nil err]))
----

Now, the previous `clean-contact` function can looks like this:

[source, clojure]
----
(defn clean-contact [params]
  (->> (clean-email params)
       (apply-or-error clean-phone)
       (apply-or-error clean-state)))
----

[options="step"]
- Looks much better.
- Can we do it better?

<<<

Define one macro for sytactic sugar.
[source, clojure]
----
(defmacro err->> [val & fns]
  (let [fns (for [f fns] `(apply-or-error ~f))]
    `(->> [~val nil]
          ~@fns)))
----


Now, here a result of using the previously defined macro:

[source, clojure]
----
(defn clean-contact [params]
  (err->> params
          clean-email
          clean-phone
          clean-state))
----

<<<

Summary:

[options="step"]
- In some languages it can be one of the most expressive way to handle errors.
- Not uses bad practices like goto or something similar.
- Can be very verbose on some languages.
- In languages like Clojure, Elixir and Haskell it can be implemented using protocols/typeclasses.

[options="step"]
**But let's go one step further!**


Monadic error handling
----------------------

**NOTE:** Explaining that is a Monad is out of scope of this talk.

[options="step"]
- Error handling defined by type.
- Most used in Haskell.
- Can be used in Clojure in same way as in Haskell.
- Other languages also can use that but much less expressivenes (can be look very ugly).

[options="step"]
.Haskell pseudocode example
[source, haskell]
----
func x = do
    a <- operationThatMightFail 10
    b <- operationThatMightFail 20
    c <- operationThatMightFail 30
    return (a + b + c)
----

<<<

Let try to do the contact validation example, but using monadic error handling and clojure.

For it I'll use link:https://github.com/niwibe/cats[cats library] and the `Either` monad.

<<<

Firstly, define the validation functions:

[source, clojure]
----
(require '[cats.monad.either :as either])

(defn clean-email [params]
  (if (re-find #"\w@\w\.\w" (params :email))
    (either/right params)
    (either/left "Please enter an email address")))

(defn clean-phone [params]
  (if (re-find #"\([0-9]{3}\) [0-9]{3}-[0-9]{4}" (params :phone))
    (either/right params)
    (either/left "Please enter your phone number in (555) 555-5555 format.")))

(defn clean-state [params]
  (case (params :state)
    "WA" (either/right params)
    "OR" (either/right params)
    (either/left "We only want people from Oregon or Washington, for some reason.")))
----

<<<

Now, the validators return a instance of Either instead of vector of two elements.

Let see how can be looks the composition of previously defined validators:

[source, clojure]
----
(require '[cats.core as m])

(defn clean-contact [params]
  (m/>>= (either/right params)
         clean-email
         clean-phone
         clean-state))
----

[options="step"]
- It looks like the last example of previous error handling way.
- It has the advantage that the composition and behavior is defined on type (you should not reapetly define different
  ways of compose different errors).
- You can create own types and mix them in the same pipeline.

<<<

What is happens if we are using third party libraries that raises Exceptions instead
of returning Either instance? The concept of Monad is generic and if your language
is sufficient expresive, you can find a elegant solution for it.

Imagine the previous example but with validators defined on third party library that
you does not have under control:

[source, clojure]
----
(require '[cats.monad.exception :as exc])

(defn clean-contact [params]
  (m/>>= (either/right params)
         (exc/wrap clean-email)
         (exc/wrap clean-phone)
         (exc/wrap clean-state)))

(clean-contact {:email "email@email.com", :phone "222 333 444", :state "WA"})

;; If something fails it will return somthing like this:
;; => #<Failure [ValidationException(...)]>

;; And if everything is ok, it will return something like:
;; => #<Success [{:email "email@email.com", :phone "222 333 444", :state "WA"}]>
----

<<<

Literature:

- http://adambard.com/blog/acceptable-error-handling-in-clojure/
- http://brehaut.net/blog/2011/error_monads
- http://yellerapp.com/posts/2014-06-27-api-error-handling.html
- https://www.fpcomplete.com/school/starting-with-haskell/basics-of-haskell/10_Error_Handling\
- http://www.lispcast.com/nil-punning
- http://swannodette.github.io/2013/08/31/asynchronous-error-handling/
- http://tersesystems.com/2012/12/27/error-handling-in-scala/
- http://lucumr.pocoo.org/2014/10/16/on-error-handling/
- http://mauricio.github.io/2014/02/17/scala-either-try-and-the-m-word.html
- http://danielwestheide.com/blog/2012/12/26/the-neophytes-guide-to-scala-part-6-error-handling-with-try.html
- http://java.dzone.com/articles/whats-wrong-java-8-part-iv

TL;DR
-----

- Throw Exception to signal unexpected failure in purely functional code.
- Use Maybe to return optional values.
- Use Either to report expected failure.


End / Q&A
---------

This talk: https://github.com/niwibe/niwi-slides/tree/master/2014/error-handling

My twitter: https://twitter.com/niwibe

My github: https://github.com/niwibe

