= OOP made "functional"
Andrey Antukh
:deckjs_theme: swiss
:deckjs_transition: fade
:customcss: extrastylesa.css
:navigation:
:status:
:source-highlighter: pygments
:pygments-style: friendly
:split:


== Who I am?

Andrey Antukh

Software Engineer at Kaleidos

- Twitter: https://twitter.com/niwibe
- Github: https://github.com/niwibe


== Author of: (mainly spam...)

link:https://github.com/funcool/cats[cats]: Category Theory abstractions for Clojure.

link:https://github.com/niwibe/suricatta[suricatta]: High level sql toolkit for clojure (backed by jooq library).

link:https://github.com/niwibe/clojure.jdbc[clojure.jdbc]: JDBC library for Clojure.

link:https://github.com/funcool/buddy-core[buddy-core]: Cryptographic api for Clojure.

link:https://github.com/funcool/buddy-auth[buddy-auth]: Auth facilities for ring based apps.

link:https://github.com/funcool/buddy-hashers[buddy-hashers]: Collection of secure password hashers for Clojure.

link:https://github.com/funcool/buddy-sign[buddy-sign]: High level message signing for Clojure.

...


== About that is this talk?

About powerful but mostly hidden features of clojure.


== Expression problem: concrete example (1)

*The Expression Problem is a new name for an old problem.*

We are developing an xmpp client, using third party XMPP library for connect to xmpp server. XMPP
has different entities, but for out example we will use that two: `RosterItem` and `Jid`.

Here a little description of these two types:

- The `RosterItem` represents an entry in the address book.
- The `Jid` represents a user identity.

Both them shares almost all fields and represents a User entity. In the XMPP terminology they have
different semantics but for out purposes is a simply `User` and we use it in interchangeably way.


== Expression problem: concrete example (2)

The library that we are using defines that hypothetical classes for represent *RosterItem* and *Jid*:

.Hypothetical data type (class) of RosterItem
[source, groovy]
----
public class RosterItem {
  public String name // "niwi"
  public String domain // "niwi.be"
  public SubscriptionType subscriptionType
}
----

.Hypothetical data type (class) of Jid
[source, groovy]
----
public class Jid {
  public String local // "niwi"
  public String domain // "niwi.be"
  public String resource // "mypc"
}
----

== Expression problem: concrete example (3)

- We need treat that data types like a User data type in almost all out code base.
- We need interact in a simply way with the third party library.
- We need a common abstraction for access in a "polymorphic way" to properties.
- We can not change the source code, because is a third party library.


== Expression problem: potential solutions (1)

*Inheritance from a common superclass*

The traditional object-oriented solution to problems of this sort is to leverage subtype
polymorphism — that is, inheritance.


We need that our user can be represented in two different ways: bare and full. For it,
ideally, both classes would implement an interface like this:

[source, groovy]
----
public interface IUser {
  public String getName()
  public String getBare()
  public String getFull()
}
----

*But it is not an option because we need modify the source code of third party library.*


== Expression problem: potential solutions (2)

*Multiple inheritance*

Another approach to the Expression Problem is multiple inheritance, in which one subclass can extend many superclasses.

.Pseudocode
[source, groovy]
----
public User extends RosterItem, Jid implements IUser {
  public String getName() { /* implementation */ }
  public String getBare() { /* implementation */ }
  public String getFull() { /* implementation */ }
}
----

But:

- it leads to complex and sometimes unpredictable class hierarchies.
- it is not very common feature on languages.


== Expression problem: potential solutions (3)

This is a one of the most popular solutions for handle the expression problem in object oriented
languages and sometimes is treated as "the solution".

Let see an example using groovy language:

[source, groovy]
----
// MyJid.groovy
public class MyJid implements IUser {
  final private Jid jid
  public MyJid(final Jid jid) { this.jid = jid }
  public String getName() { /* implementation */ }
  public String getBare() { /* implementation */ }
  public String getFull() { /* implementation */ }
}
----

But this solution has a huge number of inconveniences:

- *It breaks the identity*. You can not use an instance of your roster item as parameter to the third
  party library that you are using for connect with XMPP. You should constanctly wrapping and
  unwrapping, and this adds a lot of additional axidental complexity.
- You can't compare a `MyJid` with `Jid` with `==` operator.
- You can't use `Object.equals` because it should be symetric. If you want compate an MyJid instance
  with some other `Jid` instance, you should explicitly wrap the second one for make the compatation.
- If you want that you `MyJid` type behaves exactly that `Jid`, you should implement a proxy
  for all public methods of `Jid` class. That can be very tedious if `Jid` implements something
  like `List` interface (or any other with huge number of methods).

In my opinion, wrappers is not good solution for expression problem and requires a lot of unnecesary
work.


== Expression problem: potential solutions (4)

*Open Classes*

Consists in that a class can be reopened by anyone and at any time to add new methods.

This approach is popularized mainly by Ruby and JavaScript languages and it has similar problems that
multiple inheritance: not all languages supports it.

Example of open classes using ruby language:

[source, ruby]
----
class String
  def write_size
    self.size
  end
end
puts "hello".write_size
----

This approach also solves the problem, but in my opinion adds more problems that solves:

- It breaks namespacing (like any other solution exposed previously)
- Easy name clashing. You have no way of knowing that some other user of that class won't define
  a different and incompatible method with same name.

This technique is also known as "Monkey patching" and is well known that is not a good design pattern
for your software.


== Expression problem: potential solutions (5)

*Traits*

This is very very similar to openclasses, the unique difference is that is more safe. Because
if name clashing is happens, the compiller will notify about it and will abort the compilation.

Here an example of traits usage using rust language:

[source, rust]
----
struct Dog { name: &'static str }

trait Animal {
    fn noise(&self) -> &'static str;
}

impl Animal for Dog {
    fn noise(&self) -> &'static str {
        "woof!"
    }
}
----


== Expression problem: potential solutions (6)

*Conditionals*

This is other most common approaches to the expression problem. It consists in create a helper
class with static methods that uses conditionals (on type).

[source, groovy]
----
public class Utils {
  public static String getName(final Object data) {
    if (source instanceof RosterItem) { /* implementation */ }
    else if (source instanceof Jid) { /* implementation */ }
    else { throw IllegalArgumentException("Invalid source."); }
  }
}
----

- we are not working on abstractions: we are not really extending the type, we are creting
  a function that works on concrete types.
- can grow into not maintainable code.
- we should constantly modify the defined func for extend it.
- not performs very well.


== Expression problem: potential solutions (7)

*Overloads*

This is an improvement over the previous case. Consists on using overloads instead of conditionals.

[source, groovy]
----
public class Utils {
  public static String getName(final RosterItem data) { /* implementation */ }
  public static String getName(final Jid data) { /* implementation */ }
}
----

- performs better than conditionals.
- becomes unpredictable in the face of inheritance hierarchies.
- we are not working on abstractions: we are not really extending the type, we are creting
  a function that works on concrete types.


== Expression problem: the clojure approach (1)

Clojure is designed and written in terms of abstractions and in difference with java or
other popular languages, has different approach for work with abstractions. Like haskell (and maybe
other funcional languages), it has clear separation between types (data), abstraction (protocol),
and implementation.

There are several motivations for protocols and datatypes:

- clear separation between behavior and data.
- protocols provide high-performance dynamic polymorphism construct as an alternative to interfaces.
- protocols provide the good of interfaces.
- Avoid the 'expression problem' by allowing independent extension of the set of types, protocols,
  and implementations of protocols on types, by different parties.


== Expression problem: the clojure approach (2)

.Define our abstraction using clojure protocols
[source, clojure]
----
(ns myapp.users.protocols)

(defprotocol IUser
  "Common abstraction for access to user like objects."
  (get-name [_] "Get user name.")
  (get-bare [_] "Get bare representation of user")
  (get-full [_] "Get full representation of user"))
----

- No implementations are provided.
- Docs can be specified for the protocol and the functions.
- The above yields a set of polymorphic functions and a protocol object.
- All are namespace-qualified by the namespace enclosing the definition.
- The resulting functions dispatch on the type of their first argument, and thus must have at least one argument.
- `defprotocol` is dynamic, and does not require AOT compilation.


== Expression problem: the clojure approach (3)

.Add implementation to our types for this protocol.
[source, clojure]
----
(ns myapp.types
  (:require [myapp.users.protocols :as impl])
  (:import somelib.roster.RosterItem
           somelib.jid.Jid))

(extend-protocol impl/IUser
  RosterItem
  (get-name [o] (.-name o))
  (get-bare [o] (str (.-name o) "@" (.-domain o)))
  (get-full [o] (str (.-name o) "@" (.-domain o)))

  Jid
  (get-name [o] (.-local o))
  (get-bare [o] (str (.-local o) "@" (.-domain o)))
  (get-full [o] (str (.-local o) "@" (.-domain o) "/" (.-resource o))))
----

- extend-protocol extend own,third party classes or clojure datatypes without modifying them.


== Expression problem: the clojure approach (4)

.Usage example
[source, clojure]
----
(ns myapp.core
  (:require [myapp.users.protocols :as impl])
  (:import somelib.roster.RosterItem
           somelib.jid.Jid))

(let [jid (Jid. "niwi" "niwi.be" "mypc")
      ritem (RosterItem. "niwi2" "niwi.be" :both)]
  (println "Result: " (impl/get-bare jid))
  (println "Result: " (impl/get-bare ritem)))

;; Will print on stdout:
;; "Result: niwi@niwi.be"
;; "Result: niwi2@niwi.be"
----

- Protocols exposes namespaced functions.
- No risk of name clashing, you can have different protocols with overlaped or
  identical method names.
- In future we can add more types (own or third party) to play well with IUser abstraction.
- Covers 80%-90% of use cases of multimethods (see below).


== Polymorphism: introduction

Is the provisioning of a single interface to entities of different types.

A polymorphic type is a type whose operations can also be applied to values of some other type, or types.

There are several fundamentally different kinds of polymorphism:

- If a function denotes different and potentially heterogeneous implementations depending on a limited
  range of individually specified types and combinations, it is called *ad hoc polymorphism*. +
  _Ad hoc polymorphism is supported in many languages using *function overloading*._
- If the code is written without mention of any specific type and thus can be used transparently with any
  number of new types, it is called parametric polymorphism. +
  _In the object-oriented programming community, this is often known as *generics* or *generic programming*.
  In the functional programming community, this is often simply called *polymorphism*._
- Subtyping (or *inclusion polymorphism*) is a concept wherein a name may denote instances of many different
  classes as long as they are related by some common superclass or interface. +
  _In object-oriented programming, this is often referred to simply as *polymorphism*._


== Polymorphism: clojure approach (1)

Clojure goes beyond of standard polymorphism: multimethods.

It is commonly called *polymorphism a la carte*.

.Simple polymorphic function example:
[source, clojure]
----
(ns myapp.impl)

(defmulti get-name class)

(defmethod get-name RosterItem
  [ritem]
  (.-name ritem))

(defmethod get-name Jid
  [jid]
  (.-local jid))
----

== Polymorphism: clojure approach (2)

.Explanation of syntax
[source, clojure]
----
(defmulti get-name class)
;;        ^        ^
;;        |        ` dispatch function
;;        ` name of the method

(defmethod get-name RosterItem
  [ritem]          ;; ^
  (.-name ritem))  ;; ` dispatch mark
----


== Polymorphism: clojure approach (3)

Clojure multimethods:

- Covers standard polymorphism dispatching by type.

But also:

- You can extend and add more cases.
- You can provide own dispatcher function.
- You can dispatch by anything.
- You can build adhoc hierarchies.


== Polymorphism: clojure approach (4)

.Extending with more cases.
[source, clojure]
----
(ns myapp.extensions.fakeuser
  (:require [myapp.impl :as impl]))

(defrecord FakeUser [name])

(defmethod impl/get-name FakeUser
  [user]
  (:name user))
----


*Now, when you call impl/get-name with fake user instance
it will work as expected, returning a name.*


== Polymorphism: clojure approach (5)

.Own dispatch function
[source, clojure]
----
(defmulti do-stuff (fn [person] [(:firstname data)
                                 (:lastname data)])
(defmethod do-stuff ["Pepe" "Garcia"]
  [person]
  (println "Hello Pepe Garcia")

(defmethod do-stuff ["Pepe" "Lopez"]
  [person]
  (println "Hello Pepe Lopez")
----


== Polymorphism: clojure approach (6)

Build ad-hoc hierarchies

._derive_ is the fundamental relationship-maker
[source, clojure]
----
(derive ::circle ::shape)
(derive ::square ::shape)
----

._parents_, _ancestors_, _descendants_ and _isa?_ let you query the hierarchy
[source, clojure]
----
(parents ::circle)
;; => #{:user/shape}

(ancestors ::square)
;; => #{:user/shape}

(descendants ::shape)
;; => #{:user/circle :user/square}

(isa? ::square ::shape)
;; => true
----

== Polymorphism: clojure approach (7)

[source, clojure]
----
(derive ::triangle ::shape)

(defmulti foo class)
(defmethod foo ::circle [o] :foo-circle)
(defmethod foo ::shape [o] :foo-generic-shape)
(defmethod foo :default [o] :unexpected)

(foo ::circle)
;; => :foo-circle

(foo ::triangle)
;; => :foo-generic-shape

(foo ::bar)
;; => :unexpected
----

- It also allows resolve disambiguations with `prefer-method`
- It allows attach hierarchy to symbols and third party types.
- It allows namespaced hierarchies with `make-hierarchy`.


== End / Q&A

My twitter: https://twitter.com/niwibe

My github: https://github.com/niwibe and https://github.com/funcool

